name: Deploy

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Check file structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Directory contents ==="
          ls -la
          echo "=== src directory contents ==="
          ls -la src/
          echo "=== Checking for entry files ==="
          [ -f src/main.js ] && echo "src/main.js exists" || echo "src/main.js MISSING"
          [ -f src/index.js ] && echo "src/index.js exists" || echo "src/index.js MISSING"
      - run: npm ci
      - run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
